### ISSUE TITLE
Simplify feature set

### ISSUE THREAD

**Issue by jimtjames** [lbussell/cs4641-ml-project#9]
Reduce the number of features we have in our data. For example, replace each team's runs with the run differential. Use PCA to reduce the features further.

**Comment by lbussell** [comment]
Something like the features in

https://medium.com/@matt42kirby/predicting-baseball-pitches-33f906cbbdee

or 

https://medium.com/@alexwbell/predicting-the-next-baseball-pitch-utilizing-machine-learning-to-gain-an-advantage-cef35bbd6e26
